name: oOf merging

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_LINK: https://cfhcable.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/MIUI-WEEKLY-RELEASES/20.9.17/xiaomi.eu_multi_MI10_20.9.17_v12-11.zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get install wget
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            
       - name: Downloading and Extracting FW
         run: | 
              aria2c $ROM_LINK
              sudo unzip *.zip
              
       - name: Converting Brotli to Normal
         run: | 
              sudo aria2c https://index.download-content.cf/sdat2img.py
              sudo chmod +x sdat2img.py
              sudo brotli -d system.new.dat.br
              sudo rm -f system.new.dat.br
              sudo ./sdat2img.py system.transfer.list system.new.dat system.img
              sudo rm -rf system.new.dat system.transfer.list
              sudo brotli -d product.new.dat.br
              sudo rm -f product.new.dat.br
              sudo ./sdat2img.py product.transfer.list product.new.dat product.img
              sudo rm -rf product.new.dat product.transfer.list
              sudo brotli -d system_ext.new.dat.br
              sudo rm -f system_ext.new.dat.br
              sudo ./sdat2img.py system_ext.transfer.list system_ext.new.dat system_ext.img
              sudo rm -rf system_ext.new.dat system_ext.transfer.list
              
       - name: making
         run: |
              sudo su
              dd if=/dev/zero of=system_new.img bs=6k count=1048576
              mkfs.ext4 system_new.img
              tune2fs -c0 -i0 system_new.img
              mkdir system
              mkdir system_new
              sudo mount -o loop system_new.img system_new/
              sudo mount -o ro system.img system/
              sudo cp -v -r -p system/* system_new/
              sync
              sudo umount system/
              cd system_new
              sudo rmdir product
              cd ..
              mkdir systemop7
              sudo mount -ro loop system.img systemop7/
              sudo cp -v -r -p systemop7/product system_new/
              sudo umount systemop7/
              cd system_new/system
              sudo rm product
              sudo rm system_ext
              sudo mkdir product
              sudo mkdir system_ext
              cd ..
              cd ..
              mkdir product
              mkdir system_ext
              sudo mount -o ro product.img product/
              sudo cp -v -r -p product/* system_new/system/product/
              sync
              sudo rm -rf system_new/product
              sudo ln -s system_new/system/product system_new/product
              sudo umount product/
              sudo mount -o ro system_ext.img system_ext/
              sudo cp -v -r -p system_ext/* system_new/system/system_ext/
              sync
              sudo rm -rf system_new/system_ext
              sudo ln -s system_new/system/system_ext system_new/system/system_ext
              sudo umount system_ext/
              sudo umount system_new/
              sudo rm -rf system system.img product product.img system_ext system_ext.img
              ls
              sudo mv system_new.img system.img
              
       - name: upload ab n info
         run: |
              sudo zip memeha.zip system.img
              expect -c "
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net        
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put memeha.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
