name: oOf merging

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_LINK: https://oxygenos.oneplus.net/OnePlus8Oxygen_15.X.02_OTA_001_all_2006111749_wipe_d0f0a4b9dbde4cce.zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get install wget
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            sudo apt update 2>/dev/null | grep packages
            
       - name: Payload
         run: |
              sudo aria2c http://tdrive.manofuranium.workers.dev/payload_dumper_tool_by_ius.zip
              sudo unzip payload_dumper_tool_by_ius.zip
              cd payload_dumper
              sudo python3 -m pip install protobuf
              sudo aria2c $ROM_LINK
              sudo unzip *.zip
              sudo python3 payload_dumper.py payload.bin
              ls
              
       - name: Copying final zipp
         run: |
              mkdir lel
              sudo cp -r payload_dumper/system_ext.img lel
              sudo cp -r payload_dumper/system.img lel
              sudo cp -r payload_dumper/product.img lel
              sudo rm -rf payload_dumper

       - name: making
         run: |
              cd lel
              sudo su
              dd if=/dev/zero of=system_new.img bs=6k count=1048576
              mkfs.ext4 system_new.img
              tune2fs -c0 -i0 system_new.img
              mkdir system
              mkdir system_new
              sudo mount -o loop system_new.img system_new/
              sudo mount -o ro system.img system/
              sudo cp -v -r -p system/* system_new/
              sync
              sudo umount system/
              cd system_new
              sudo rmdir product
              cd ..
              mkdir systemop7
              sudo mount -ro loop system.img systemop7/
              sudo cp -v -r -p systemop7/product system_new/
              sudo umount systemop7/
              cd system_new/system
              sudo rm product
              sudo rm system_ext
              sudo mkdir product
              sudo mkdir system_ext
              cd ..
              cd ..
              mkdir product
              mkdir system_ext
              sudo mount -o ro product.img product/
              sudo cp -v -r -p product/* system_new/system/product/
              sync
              sudo umount product/
              sudo mount -o ro system_ext.img system_ext/
              sudo cp -v -r -p system_ext/* system_new/system/system_ext/
              sync
              sudo umount system_ext/
              sudo umount system_new/
              sudo rm -rf system system.img product product.img system_ext system_ext.img
              ls
              sudo mv system_new.img system.img
         
       - name: upload final zip
         run: 
              cd lel
              sudo zip op8test3.zip system.img
     
       - name: upload final zip
         run: |
              cd lel
              expect -c "
              spawn sftp ruiii@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/rui-ports/dumps\r\"
              set timeout -1
              send \"put op8test3.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
